import { useCallback, useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { archiveLmsCourse, createLmsCourse, deleteLmsCourse, getLmsCategories, getLmsCourses, publishLmsCourse, updateLmsCourse } from "../api/lms"

const emptyForm = { title: "", description: "", categoryId: "", difficulty: "beginner", estimatedDurationMinutes: "", learningOutcomes: "", tags: "", badge: "", coverImage: "", icon: "" }
const idOf = (item) => item.id ?? item._id
const statusOf = (course) => course.status ?? (course.isPublished ? "PUBLISHED" : "DRAFT")

export default function LmsCourses() {
  const [courses, setCourses] = useState([]); const [categories, setCategories] = useState([])
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null)
  const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("")
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [courseResult, categoryResult] = await Promise.all([getLmsCourses({ search }), getLmsCategories()]); setCourses(courseResult.items); setCategories(categoryResult) } catch (err) { setError(err?.response?.data?.message || "Could not load LMS courses.") } finally { setLoading(false) } }, [search])
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer) }, [load])
  function edit(course) { setEditing(course); setForm({ title: course.title || "", description: course.description || "", categoryId: typeof course.category === "object" ? idOf(course.category) : course.category || "", difficulty: course.difficulty || "beginner", estimatedDurationMinutes: course.estimatedDurationMinutes ?? "", learningOutcomes: (course.learningOutcomes || []).join("\n"), tags: (course.tags || []).join(", "), badge: course.badge || "", coverImage: course.coverImage || "", icon: course.icon || "" }) }
  async function submit(event) { event.preventDefault(); if (!form.title.trim() || !form.categoryId) return setError("A course title and category are required."); setSaving(true); setError(""); try { const payload = { title: form.title.trim(), description: form.description.trim(), categoryId: form.categoryId, difficulty: form.difficulty, badge: form.badge || undefined, coverImage: form.coverImage.trim() || undefined, icon: form.icon.trim() || undefined, estimatedDurationMinutes: form.estimatedDurationMinutes === "" ? 0 : Number(form.estimatedDurationMinutes), learningOutcomes: form.learningOutcomes.split("\n").map((item) => item.trim()).filter(Boolean), tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean) }; if (editing) await updateLmsCourse(idOf(editing), payload); else await createLmsCourse(payload); setEditing(null); setForm(emptyForm); await load() } catch (err) { setError(err?.response?.data?.message || "Could not save the course.") } finally { setSaving(false) } }
  async function action(course, fn) { setError(""); try { await fn(idOf(course)); await load() } catch (err) { setError(err?.response?.data?.message || "The course action failed.") } }
  return <div className="max-w-7xl">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">LMS Courses</h1><p className="text-sm text-slate-500">Create, publish and maintain your training catalog.</p></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search courses" className="rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-400" /></div>
    {error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</div>}
    <div className="grid gap-5 xl:grid-cols-[370px_1fr]">
      <form onSubmit={submit} className="h-fit rounded-xl border border-slate-200 bg-white p-5 space-y-3"><h2 className="font-semibold text-slate-900">{editing ? "Edit course" : "New course"}</h2><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Course title" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-400" /><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Course description" rows="3" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-400" /><select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Select category</option>{categories.map((category) => <option key={idOf(category)} value={idOf(category)}>{category.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><select value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">{["beginner", "intermediate", "advanced", "professional"].map((value) => <option key={value}>{value}</option>)}</select><input type="number" min="0" value={form.estimatedDurationMinutes} onChange={(e) => setForm({ ...form, estimatedDurationMinutes: e.target.value })} placeholder="Duration (mins)" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /></div><div className="grid grid-cols-2 gap-3"><input value={form.coverImage} onChange={(e) => setForm({ ...form, coverImage: e.target.value })} placeholder="Cover image URL" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })} placeholder="Icon URL or name" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /></div><input value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} placeholder="Tags, separated by commas" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /><textarea value={form.learningOutcomes} onChange={(e) => setForm({ ...form, learningOutcomes: e.target.value })} placeholder="Learning outcomes, one per line" rows="3" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /><div className="flex gap-2"><button disabled={saving} className="rounded-lg bg-[#1A2F5E] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Saving..." : editing ? "Save changes" : "Create course"}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(emptyForm) }} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">Cancel</button>}</div></form>
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">{loading ? <p className="p-6 text-sm text-slate-500">Loading courses...</p> : courses.length === 0 ? <p className="p-6 text-sm text-slate-500">No courses found.</p> : courses.map((course) => <div key={idOf(course)} className="border-b border-slate-100 p-5 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold text-slate-800">{course.title || course.name}</h3><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600">{statusOf(course)}</span></div><p className="mt-1 text-sm text-slate-500">{course.description || "No description"}</p><p className="mt-2 text-xs text-slate-400">{course.category?.name || "Uncategorized"} · {course.difficulty || "beginner"} · {course.estimatedDurationMinutes ? `${course.estimatedDurationMinutes} mins` : "Duration not set"}</p></div><div className="flex flex-wrap gap-2"><Link to={`/dashboard/lms/courses/${idOf(course)}`} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">Content</Link><button onClick={() => edit(course)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-blue-600">Edit</button>{statusOf(course).toLowerCase() === "published" ? <button onClick={() => action(course, archiveLmsCourse)} className="rounded-lg border border-amber-200 px-3 py-1.5 text-xs font-semibold text-amber-700">Archive</button> : <button onClick={() => action(course, publishLmsCourse)} className="rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-semibold text-emerald-700">Publish</button>}<button onClick={() => window.confirm(`Delete "${course.title || course.name}"?`) && action(course, deleteLmsCourse)} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-600">Delete</button></div></div></div>)}</div>
    </div>
  </div>
}
