import { useCallback, useEffect, useState } from "react"
import { approveEnrollment, getCourseEnrollments, getLmsCourses } from "../api/lms"

const idOf = (item) => item.id ?? item._id
const learnerName = (item) => item.user?.name || [item.user?.firstName, item.user?.lastName].filter(Boolean).join(" ") || item.learner?.name || item.user?.email || "Learner"

export default function LmsEnrollments() {
  const [courses, setCourses] = useState([]); const [courseId, setCourseId] = useState(""); const [enrollments, setEnrollments] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("")
  const loadCourses = useCallback(async () => { try { const result = await getLmsCourses({ limit: 100 }); setCourses(result.items) } catch (err) { setError(err?.response?.data?.message || "Could not load courses.") } }, [])
  const loadEnrollments = useCallback(async () => { if (!courseId) return setEnrollments([]); setLoading(true); setError(""); try { const result = await getCourseEnrollments(courseId); setEnrollments(result.items) } catch (err) { setError(err?.response?.data?.message || "Could not load enrollments.") } finally { setLoading(false) } }, [courseId])
  useEffect(() => { loadCourses() }, [loadCourses]); useEffect(() => { loadEnrollments() }, [loadEnrollments])
  async function approve(enrollment) { try { await approveEnrollment(idOf(enrollment)); await loadEnrollments() } catch (err) { setError(err?.response?.data?.message || "Could not approve this enrollment.") } }
  return <div className="max-w-6xl"><div className="mb-6"><h1 className="text-xl font-bold text-slate-900">LMS Enrollments</h1><p className="text-sm text-slate-500">Review and approve learner access for each course.</p></div>{error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</div>}<div className="mb-5 flex gap-3"><select value={courseId} onChange={(e) => setCourseId(e.target.value)} className="w-full max-w-md rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">Select a course</option>{courses.map((course) => <option key={idOf(course)} value={idOf(course)}>{course.title || course.name}</option>)}</select><button onClick={loadEnrollments} disabled={!courseId || loading} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 disabled:opacity-50">Refresh</button></div>{!courseId ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Choose a course to manage its enrollments.</div> : <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">{loading ? <p className="p-6 text-sm text-slate-500">Loading enrollments...</p> : enrollments.length === 0 ? <p className="p-6 text-sm text-slate-500">No enrollments found for this course.</p> : <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Learner</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Progress</th><th className="px-5 py-3">Action</th></tr></thead><tbody>{enrollments.map((enrollment) => <tr key={idOf(enrollment)} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-medium text-slate-800">{learnerName(enrollment)}</p><p className="text-xs text-slate-500">{enrollment.user?.email || enrollment.learner?.email || ""}</p></td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{enrollment.status || "PENDING"}</span></td><td className="px-5 py-4 text-slate-600">{enrollment.progress ?? 0}%</td><td className="px-5 py-4">{(enrollment.status || "").toUpperCase() === "PENDING" ? <button onClick={() => approve(enrollment)} className="rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-semibold text-emerald-700">Approve</button> : <span className="text-xs text-slate-400">No action required</span>}</td></tr>)}</tbody></table>}</div>}</div>
}
