import { useCallback, useEffect, useMemo, useState } from "react";
import PageLayout from "../../../components/PageLayout";
import { getUsersPerformance } from "../../../api/services/employees";

const number = (value) => Number.isFinite(value) ? value.toFixed(2) : "0.00";

const Performance = () => {
  const [employees, setEmployees] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); setError(""); const result = await getUsersPerformance(); setEmployees(Array.isArray(result.data) ? result.data : []); } catch (err) { setError(err?.response?.data?.message || "Unable to fetch employee performance."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  const averages = useMemo(() => employees.reduce((value, employee) => ({ score: value.score + (employee.performanceScore || 0), completion: value.completion + (employee.completionRate || 0), violations: value.violations + (employee.attendanceViolations || 0) }), { score: 0, completion: 0, violations: 0 }), [employees]);
  const count = employees.length || 1;
  return <PageLayout title="Performance" description="Analyze employee performance metrics."><div className="space-y-5"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">Scores combine task completion, work hours, and attendance violations.</p><button type="button" onClick={load} disabled={loading} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm disabled:opacity-60">{loading ? "Loading..." : "Refresh"}</button></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-sm text-slate-500">Average performance</p><p className="text-2xl font-bold">{number(averages.score / count)}</p></div><div className="rounded-xl border p-4"><p className="text-sm text-slate-500">Average completion</p><p className="text-2xl font-bold">{number(averages.completion / count)}%</p></div><div className="rounded-xl border p-4"><p className="text-sm text-slate-500">Attendance violations</p><p className="text-2xl font-bold">{averages.violations}</p></div></div>{error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="px-5 py-4">Employee</th><th className="px-5 py-4">Department / role</th><th className="px-5 py-4">Tasks</th><th className="px-5 py-4">Attendance</th><th className="px-5 py-4">Average hours</th><th className="px-5 py-4">Violations</th><th className="px-5 py-4">Score</th></tr></thead><tbody>{loading ? <tr><td colSpan="7" className="px-5 py-16 text-center">Loading performance data...</td></tr> : employees.length === 0 ? <tr><td colSpan="7" className="px-5 py-16 text-center">No employee performance data found.</td></tr> : employees.map((employee) => <tr key={employee.userId} className="border-t"><td className="px-5 py-4"><p className="font-medium">{employee.employeeName}</p><p className="text-xs text-slate-500">{employee.userId}</p></td><td className="px-5 py-4">{employee.department || "-"}<p className="text-xs text-slate-500">{employee.role}</p></td><td className="px-5 py-4">{employee.completedTasks || 0}/{employee.totalTasks || 0} ({number(employee.completionRate)}%)</td><td className="px-5 py-4">{employee.totalAttendance || 0} records</td><td className="px-5 py-4">{number(employee.averageWorkingHours)}h</td><td className="px-5 py-4">{employee.attendanceViolations || 0}</td><td className="px-5 py-4 font-semibold">{number(employee.performanceScore)}</td></tr>)}</tbody></table></div></div></div></PageLayout>;
};
export default Performance;
