import { useCallback, useEffect, useMemo, useState } from "react";
import PageLayout from "../../../components/PageLayout";
import { getAuditLogs } from "../../../api/services/compliance";

const initialFilters = { page: 1, limit: 25, action: "" };
const date = (value) => value ? new Date(value).toLocaleString("en-IN") : "-";

const Audits = () => {
  const [filters, setFilters] = useState(initialFilters); const [logs, setLogs] = useState([]); const [pagination, setPagination] = useState({ page: 1, limit: 25, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const query = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== "")), [filters]);
  const load = useCallback(async () => { try { setLoading(true); setError(""); const result = await getAuditLogs(query); setLogs(Array.isArray(result.data?.logs) ? result.data.logs : []); setPagination(result.pagination || { page: 1, limit: 25, total: 0 }); } catch (err) { setError(err?.response?.data?.message || "Unable to fetch audit logs."); } finally { setLoading(false); } }, [query]);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  const update = (key, value) => setFilters((current) => ({ ...current, page: key === "page" ? value : 1, [key]: value }));
  const pages = Math.max(1, Math.ceil(pagination.total / pagination.limit));
  return <PageLayout title="Audits" description="Review the immutable compliance audit trail."><div className="space-y-5"><div className="flex justify-between rounded-xl border border-slate-200 bg-slate-50 p-4"><input type="search" value={filters.action} onChange={(event) => update("action", event.target.value)} placeholder="Filter by exact action" className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm" /><button type="button" onClick={load} disabled={loading} className="rounded-lg border border-slate-300 bg-white px-4 text-sm disabled:opacity-60">Refresh</button></div>{error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="px-5 py-4">Log ID</th><th className="px-5 py-4">Action</th><th className="px-5 py-4">Actor</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Metadata</th><th className="px-5 py-4">Timestamp</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="px-5 py-16 text-center">Loading audit logs...</td></tr> : logs.length === 0 ? <tr><td colSpan="6" className="px-5 py-16 text-center">No audit logs found.</td></tr> : logs.map((log) => <tr key={log.id} className="border-t"><td className="px-5 py-4">{log.id}</td><td className="px-5 py-4">{log.action}</td><td className="px-5 py-4">{log.actorId}</td><td className="px-5 py-4">{log.actorRole}</td><td className="max-w-sm break-all px-5 py-4 font-mono text-xs">{log.meta ? JSON.stringify(log.meta) : "-"}</td><td className="px-5 py-4">{date(log.createdAt)}</td></tr>)}</tbody></table></div></div><div className="flex justify-end gap-3"><button type="button" onClick={() => update("page", pagination.page - 1)} disabled={loading || pagination.page <= 1} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><span>Page {pagination.page} of {pages}</span><button type="button" onClick={() => update("page", pagination.page + 1)} disabled={loading || pagination.page >= pages} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></div></div></PageLayout>;
};
export default Audits;
