import { useCallback, useEffect, useState } from "react";
import PageLayout from "../../../components/PageLayout";
import { getSOSAlerts } from "../../../api/services/sos";

const ActiveSOS = () => {
  const [status, setStatus] = useState("OPEN"); const [offset, setOffset] = useState(0); const [alerts, setAlerts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const limit = 25;
  const load = useCallback(async () => { try { setLoading(true); setError(""); const result = await getSOSAlerts({ status, limit, offset }); setAlerts(Array.isArray(result.data) ? result.data : []); } catch (err) { setError(err?.response?.data?.message || "Unable to fetch SOS alerts."); } finally { setLoading(false); } }, [status, offset]);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  const location = (point) => { const [longitude, latitude] = point?.coordinates || []; return Number.isFinite(latitude) ? `${latitude.toFixed(5)}, ${longitude.toFixed(5)}` : "-"; };
  return <PageLayout title="Active SOS" description="Manage active SOS requests."><div className="space-y-5"><div className="flex justify-between rounded-xl border border-slate-200 bg-slate-50 p-4"><select value={status} onChange={(event) => { setStatus(event.target.value); setOffset(0); }} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="OPEN">Open</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="RESOLVED">Resolved</option><option value="">All statuses</option></select><button type="button" onClick={load} disabled={loading} className="rounded-lg border border-slate-300 bg-white px-4 text-sm disabled:opacity-60">Refresh</button></div>{error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="px-5 py-4">SOS ID</th><th className="px-5 py-4">Employee ID</th><th className="px-5 py-4">Reported</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Escalation</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="px-5 py-16 text-center">Loading SOS alerts...</td></tr> : alerts.length === 0 ? <tr><td colSpan="6" className="px-5 py-16 text-center">No SOS alerts found.</td></tr> : alerts.map((alert) => <tr key={alert.id || alert._id} className="border-t"><td className="px-5 py-4">{alert.id}</td><td className="px-5 py-4">{alert.userId}</td><td className="px-5 py-4">{alert.createdAt ? new Date(alert.createdAt).toLocaleString("en-IN") : "-"}</td><td className="px-5 py-4">{location(alert.location)}</td><td className="px-5 py-4">Level {alert.escalationLevel ?? 0}</td><td className="px-5 py-4">{alert.status}</td></tr>)}</tbody></table></div></div><div className="flex justify-end gap-3"><button type="button" onClick={() => setOffset(Math.max(0, offset - limit))} disabled={loading || offset === 0} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><button type="button" onClick={() => setOffset(offset + limit)} disabled={loading || alerts.length < limit} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></div></div></PageLayout>;
};
export default ActiveSOS;
