export enum Permission {
  // Common Permissions
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LIST = "LIST",
  EXPORT = "EXPORT",

  // User Management
  VIEW_USERS = "VIEW_USERS",
  CREATE_USERS = "CREATE_USERS",
  EDIT_USERS = "EDIT_USERS",
  DELETE_USERS = "DELETE_USERS",
  ASSIGN_ROLES = "ASSIGN_ROLES",

  // Roster Management
  VIEW_ROSTER = "VIEW_ROSTER",
  CREATE_ROSTER = "CREATE_ROSTER",
  EDIT_ROSTER = "EDIT_ROSTER",
  DELETE_ROSTER = "DELETE_ROSTER",
  PUBLISH_ROSTER = "PUBLISH_ROSTER",

  // Attendance
  VIEW_ATTENDANCE = "VIEW_ATTENDANCE",
  MARK_ATTENDANCE = "MARK_ATTENDANCE",
  EDIT_ATTENDANCE = "EDIT_ATTENDANCE",
  APPROVE_ATTENDANCE = "APPROVE_ATTENDANCE",

  // Shift Management
  VIEW_SHIFT = "VIEW_SHIFT",
  CREATE_SHIFT = "CREATE_SHIFT",
  EDIT_SHIFT = "EDIT_SHIFT",
  DELETE_SHIFT = "DELETE_SHIFT",

  // Gig Management
  VIEW_GIGS = "VIEW_GIGS",
  CREATE_GIGS = "CREATE_GIGS",
  EDIT_GIGS = "EDIT_GIGS",
  DELETE_GIGS = "DELETE_GIGS",

  // Booking Management
  VIEW_BOOKINGS = "VIEW_BOOKINGS",
  CREATE_BOOKINGS = "CREATE_BOOKINGS",
  EDIT_BOOKINGS = "EDIT_BOOKINGS",
  CANCEL_BOOKINGS = "CANCEL_BOOKINGS",

  // Payment
  VIEW_PAYMENTS = "VIEW_PAYMENTS",
  PROCESS_PAYMENTS = "PROCESS_PAYMENTS",
  REFUND_PAYMENTS = "REFUND_PAYMENTS",

  // Reports
  VIEW_REPORTS = "VIEW_REPORTS",
  GENERATE_REPORTS = "GENERATE_REPORTS",

  // Settings
  VIEW_SETTINGS = "VIEW_SETTINGS",
  EDIT_SETTINGS = "EDIT_SETTINGS",

  // Recruitment
  VIEW_JOBS = "VIEW_JOBS",
  POST_JOBS = "POST_JOBS",
  EDIT_JOBS = "EDIT_JOBS",
  DELETE_JOBS = "DELETE_JOBS",
  VIEW_APPLICATIONS = "VIEW_APPLICATIONS",
  MANAGE_APPLICATIONS = "MANAGE_APPLICATIONS",

  // Tasks
  VIEW_TASKS = "VIEW_TASKS",
  CREATE_TASKS = "CREATE_TASKS",
  EDIT_TASKS = "EDIT_TASKS",
  DELETE_TASKS = "DELETE_TASKS",
  ASSIGN_TASKS = "ASSIGN_TASKS",

  // LMS
  VIEW_COURSES = "VIEW_COURSES",
  CREATE_COURSES = "CREATE_COURSES",
  EDIT_COURSES = "EDIT_COURSES",
  DELETE_COURSES = "DELETE_COURSES",
  ENROLL_COURSES = "ENROLL_COURSES",

  // Admin Functions
  MANAGE_RBAC = "MANAGE_RBAC",
  MANAGE_ADMINS = "MANAGE_ADMINS",
  VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",
}

export enum ResourceType {
  USERS = "USERS",
  ROSTER = "ROSTER",
  ATTENDANCE = "ATTENDANCE",
  SHIFT = "SHIFT",
  GIGS = "GIGS",
  BOOKINGS = "BOOKINGS",
  PAYMENTS = "PAYMENTS",
  REPORTS = "REPORTS",
  SETTINGS = "SETTINGS",
  JOBS = "JOBS",
  APPLICATIONS = "APPLICATIONS",
  TASKS = "TASKS",
  COURSES = "COURSES",
  RBAC = "RBAC",
  ADMINS = "ADMINS",
  AUDIT_LOG = "AUDIT_LOG",
}
