export enum UserRole {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    EMPLOYEE = 'EMPLOYEE',
    STUDENT = 'STUDENT',
    PROFESSIONAL = 'PROFESSIONAL',
    HR = "HR"
}

export enum UserStatus {
    CREATED = "CREATED",
    ACTIVE = "ACTIVE",
    SUSPENDED = "SUSPENDED"
}

export enum UserProfession {
    CAPTAIN = "Captain",
    CHEF = "Chef",
    WAITER = "Waiter",
    BARTENDER = "Bartender",
    HOSTESS = "Hostess",
    MANAGEMENT = "Management",
    STUDENT = "Student",
    OTHER = "Other"
}

export enum UserDepartmentType {
    FRONT_OFFICE = "FRONT_OFFICE",
    HOUSEKEEPING = "HOUSEKEEPING",
    FOOD_AND_BEVERAGE = "FOOD_AND_BEVERAGE",
    KITCHEN = "KITCHEN",
    ENGINEERING_AND_MAINTENANCE = "ENGINEERING_AND_MAINTENANCE",
    SECURITY = "SECURITY",
    HUMAN_RESOURCES = "HUMAN_RESOURCES",
    FINANCE_AND_ACCOUNTS = "FINANCE_AND_ACCOUNTS",
    SALES_AND_MARKETING = "SALES_AND_MARKETING",
    IT = "IT",
}

export enum UserDepartmentRole {
    // Front Office
    FRONT_OFFICE_MANAGER = "FRONT_OFFICE_MANAGER",
    DUTY_MANAGER = "DUTY_MANAGER",
    RECEPTIONIST = "RECEPTIONIST",
    GUEST_RELATIONS_EXECUTIVE = "GUEST_RELATIONS_EXECUTIVE",
    CONCIERGE = "CONCIERGE",
    BELLBOY = "BELLBOY",

    // Housekeeping
    HOUSEKEEPING_MANAGER = "HOUSEKEEPING_MANAGER",
    HOUSEKEEPING_SUPERVISOR = "HOUSEKEEPING_SUPERVISOR",
    ROOM_ATTENDANT = "ROOM_ATTENDANT",
    LAUNDRY_ATTENDANT = "LAUNDRY_ATTENDANT",
    PUBLIC_AREA_ATTENDANT = "PUBLIC_AREA_ATTENDANT",

    // Food & Beverage
    FNB_MANAGER = "FNB_MANAGER",
    RESTAURANT_MANAGER = "RESTAURANT_MANAGER",
    CAPTAIN = "CAPTAIN",
    WAITER = "WAITER",
    BARTENDER = "BARTENDER",
    BANQUET_EXECUTIVE = "BANQUET_EXECUTIVE",

    // Kitchen
    EXECUTIVE_CHEF = "EXECUTIVE_CHEF",
    SOUS_CHEF = "SOUS_CHEF",
    CHEF_DE_PARTIE = "CHEF_DE_PARTIE",
    COMMIS_CHEF = "COMMIS_CHEF",
    BAKERY_CHEF = "BAKERY_CHEF",
    PASTRY_CHEF = "PASTRY_CHEF",

    // Engineering
    ENGINEERING_MANAGER = "ENGINEERING_MANAGER",
    MAINTENANCE_SUPERVISOR = "MAINTENANCE_SUPERVISOR",
    ELECTRICIAN = "ELECTRICIAN",
    PLUMBER = "PLUMBER",
    HVAC_TECHNICIAN = "HVAC_TECHNICIAN",

    // Security
    SECURITY_MANAGER = "SECURITY_MANAGER",
    SECURITY_SUPERVISOR = "SECURITY_SUPERVISOR",
    SECURITY_OFFICER = "SECURITY_OFFICER",
    SECURITY_GUARD = "SECURITY_GUARD",

    // HR
    HR_MANAGER = "HR_MANAGER",
    HR_EXECUTIVE = "HR_EXECUTIVE",
    RECRUITER = "RECRUITER",
    TRAINING_COORDINATOR = "TRAINING_COORDINATOR",

    // Finance
    FINANCE_MANAGER = "FINANCE_MANAGER",
    ACCOUNTANT = "ACCOUNTANT",
    AUDITOR = "AUDITOR",
    CASHIER = "CASHIER",

    // Sales & Marketing
    SALES_MANAGER = "SALES_MANAGER",
    SALES_EXECUTIVE = "SALES_EXECUTIVE",
    CORPORATE_SALES_EXECUTIVE = "CORPORATE_SALES_EXECUTIVE",
    MARKETING_EXECUTIVE = "MARKETING_EXECUTIVE",

    // IT
    IT_MANAGER = "IT_MANAGER",
    SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR",
    NETWORK_ENGINEER = "NETWORK_ENGINEER",
    IT_SUPPORT_EXECUTIVE = "IT_SUPPORT_EXECUTIVE",
}

export enum UserAvailability {
    WEEKDAYS = "Weekdays",
    WEEKENDS = "Weekends",
    WEEKDAYS_AND_WEEKENDS = "Both weekdays & weekends",
    FLEXIBLE = "Flexible / Any time"
}

export enum YearsOfExperience {
    LESS_THAN_ONE = "Less than 1 year",
    ONE_TO_TWO = "1–2 years",
    THREE_TO_FIVE = "3–5 years",
    FIVE_TO_TEN = "5–10 years",
    MORE_THAN_TEN = "10+ years"
}